// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:52:40 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int PmTimeProcPtr_ae9b2a7b(void* time_info) {
	return timeProcPtrAE9B2A7B(time_info);
}

