// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 10 Sep 2016 16:45:06 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "portmidi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PmTimeProcPtr_ae9b2a7b is a proxy for callback PmTimeProcPtr.
int PmTimeProcPtr_ae9b2a7b(void* time_info);

