// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 10 Sep 2016 16:45:06 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int PmTimeProcPtr_ae9b2a7b(void* time_info) {
	return timeProcPtrAE9B2A7B(time_info);
}

