// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 08 Sep 2016 18:36:12 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package pm provides Go bindings for portmidi.
*/
package pm
