// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:52:40 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

/*
Package pm provides Go bindings for portmidi.
*/
package pm
